name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: crystal-lang/install-crystal@v1
    - uses: actions/checkout@v4
    - name: Run test
      run: crystal eval "puts 1337"
