name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        crystal-version: ['1.17.1', 'latest']

    runs-on: ubuntu-22.04
    steps:
    - name: "Set up Crystal ${{ matrix.crystal-version }}"
      uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ matrix.crystal-version }}
    - uses: actions/checkout@v4
    - name: Run test
      run: crystal eval "puts 1337"
